#!/usr/bin/env python3
"""Write Folio/Localization/Localizable.xcstrings for every shipped locale."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "Folio" / "Localization" / "Localizable.xcstrings"

LOCALES = [
    "en", "es", "fr", "de", "it", "pt-BR", "pt-PT", "nl", "da", "sv", "nb", "fi",
    "pl", "cs", "hu", "ro", "el", "tr", "ru", "uk", "ar", "he", "hi", "th", "vi",
    "id", "ja", "ko", "zh-Hans", "zh-Hant",
]

# key -> locale -> value
EN = {
    "app.name": "Folio",
    "group.organize": "Organize",
    "group.edit": "Edit",
    "group.reduce": "Reduce",
    "group.stamp": "Stamp",
    "group.convert": "Convert",
    "group.secure": "Secure",
    "recents": "Recents",
    "recents.clear": "Clear",
    "recents.empty": "No recent files",
    "tool.pages": "Pages",
    "tool.edit": "Edit",
    "tool.merge": "Merge",
    "tool.split": "Split",
    "tool.compress": "Compress",
    "tool.watermark": "Watermark",
    "tool.pageNumbers": "Page numbers",
    "tool.imagesToPDF": "Images to PDF",
    "tool.pdfToImages": "PDF to images",
    "tool.extractText": "Extract text",
    "tool.ocr": "OCR",
    "tool.protect": "Protect",
    "tool.unlock": "Unlock",
    "tool.redact": "Redact",
    "stage.pages": "Pages",
    "stage.read": "Read",
    "toolbar.rotate": "Rotate right",
    "toolbar.rotateCCW": "Rotate left",
    "toolbar.delete": "Remove from workspace",
    "toolbar.addFiles": "Add files",
    "toolbar.inspector": "Inspector",
    "toolbar.settings": "Settings",
    "empty.headline": "Drop a PDF",
    "empty.hint": "Files stay on this Mac. Export never overwrites the original unless you ask.",
    "empty.drop": "Drop PDFs or images, or click to choose",
    "export": "Export…",
    "export.saved": "Saved",
    "export.replace": "Replace original",
    "export.replaceConfirm": "Replace the original file?",
    "export.replaceMessage": "This cannot be undone from Folio.",
    "export.flatten": "Flatten annotations",
    "inspector.pages": "Pages",
    "inspector.size": "Size",
    "inspector.document": "Document",
    "compress.after": "After",
    "compress.before": "Before",
    "compress.preset": "Preset",
    "compress.small": "Small (email)",
    "compress.medium": "Medium",
    "compress.high": "High quality",
    "compress.grayscale": "Grayscale",
    "split.mode": "Split",
    "split.selected": "Selected pages",
    "split.ranges": "Ranges",
    "split.rangesHint": "1-3, 7, 10-",
    "split.every": "Every N pages",
    "split.eachPage": "Each page",
    "split.oneFilePerRange": "One file per range",
    "merge.help": "Arrange pages in the tray, then export one file.",
    "watermark.text": "Watermark text",
    "watermark.position": "Position",
    "watermark.position.center": "Center",
    "watermark.position.tile": "Tile",
    "watermark.position.topLeft": "Top left",
    "watermark.position.topRight": "Top right",
    "watermark.position.bottomLeft": "Bottom left",
    "watermark.position.bottomRight": "Bottom right",
    "watermark.opacity": "Opacity",
    "watermark.rotation": "Rotation",
    "pageNumbers.format": "Format",
    "pageNumbers.format.number": "1",
    "pageNumbers.format.of": "1 / N",
    "pageNumbers.format.page": "Page 1",
    "pageNumbers.position": "Position",
    "pageNumbers.position.headerLeft": "Header left",
    "pageNumbers.position.headerCenter": "Header center",
    "pageNumbers.position.headerRight": "Header right",
    "pageNumbers.position.footerLeft": "Footer left",
    "pageNumbers.position.footerCenter": "Footer center",
    "pageNumbers.position.footerRight": "Footer right",
    "pageNumbers.startAt": "Start at",
    "pageNumbers.skipFirst": "Skip first page",
    "images.pageSize": "Page size",
    "images.pageSize.imageSize": "Image size",
    "images.pageSize.letter": "Letter",
    "images.pageSize.a4": "A4",
    "images.format": "Format",
    "images.dpi": "DPI",
    "extract.help": "Export the text layer of these pages as a .txt file.",
    "ocr.help": "Recognize text on scanned pages and write a searchable PDF. On this Mac only.",
    "unlock.help": "Write an unlocked copy. Folio needs the password you used when opening the file.",
    "protect.password": "Password",
    "protect.confirm": "Confirm password",
    "protect.owner": "Owner password (optional)",
    "redact.warning": "Redacted pages become images so the hidden text cannot be recovered.",
    "redact.fill": "Fill",
    "redact.fill.black": "Black",
    "redact.fill.white": "White",
    "redact.entirePage": "Redact entire page",
    "metadata.title": "Title",
    "metadata.author": "Author",
    "metadata.subject": "Subject",
    "settings.title": "Settings",
    "settings.language": "Language",
    "settings.language.system": "System",
    "settings.language.relaunch": "The interface language updates when you choose one.",
    "pages.selectRange": "Select",
    "pages.selectRangeHint": "Pages or ranges",
    "pages.selectRangeHelp": "Type page numbers or ranges. Delete and other actions apply to this selection.",
    "settings.copyright": "Copyright © 2026 TGthms & Grok",
    "settings.repo": "GitHub",
    "menu.open": "Open…",
    "menu.save": "Save…",
    "menu.export": "Export…",
    "menu.tools": "Tools",
    "menu.help": "Folio Help",
    "command.addFiles": "Add files…",
    "command.save": "Save",
    "command.export": "Export…",
    "command.palette": "Search",
    "error.emptyWorkspace": "Add pages before exporting.",
    "error.unreadable": "Folio could not read that file.",
    "error.encrypted": "This PDF is locked.",
    "error.writeFailed": "Folio could not write the file.",
    "error.cancelled": "Export cancelled.",
    "error.diskFull": "The disk is full.",
    "error.passwordMismatch": "Passwords do not match.",
    "error.noPassword": "Enter a password.",
    "error.invalidRange": "That page range is not valid.",
    "error.outOfBounds": "That page number is out of range.",
    "suffix.merged": " – merged",
    "suffix.part": " – part",
    "suffix.compressed": " – compressed",
    "suffix.stamped": " – stamped",
    "suffix.locked": " – locked",
    "suffix.unlocked": " – unlocked",
    "suffix.searchable": " – searchable",
    "suffix.redacted": " – redacted",
    "suffix.page": " – page",
    "suffix.text": " – text",
    "page_count": "%d pages",
    "done": "Done",
    "cancel": "Cancel",
    "ok": "OK",
    "password.prompt": "This PDF is locked",
    "password.unlock": "Password",
    "pages.reverse": "Reverse order",
    "pages.duplicate": "Duplicate",
    "pages.insertBlank": "Insert blank page",
    "pages.removeBlank": "Remove blank pages",
    "inspector.encrypted": "Encrypted",
    "inspector.yes": "Yes",
    "inspector.no": "No",
    "menu.print": "Print…",
    "menu.go": "Go",
    "nav.next": "Next Page",
    "nav.previous": "Previous Page",
    "nav.first": "First Page",
    "nav.last": "Last Page",
    "nav.selectAll": "Select All Pages",
    "edit.select": "Select",
    "edit.help": "Scroll the PDF as usual. Highlight and underline follow a text selection. Draw, text, and crop use a drag. Save writes the marks into the file.",
    "edit.highlight": "Highlight",
    "edit.underline": "Underline",
    "edit.textBox": "Text box",
    "edit.draw": "Draw",
    "edit.cropMode": "Crop",
    "edit.crop": "Crop selected pages",
    "edit.clearCrop": "Clear crop",
    "edit.replaceImage": "Replace page with image…",
    "edit.clearMarks": "Clear marks on selection",
    "edit.textPrompt": "Text",
    "suffix.edited": " – edited",
    "size.zero": "0 KB",
    "size.bytesUnit": "bytes",
    "size.kb": "KB",
    "size.mb": "MB",
    "size.gb": "GB",
    "language.en": "English",
    "language.es": "Spanish",
    "language.fr": "French",
    "language.de": "German",
    "language.it": "Italian",
    "language.pt-BR": "Portuguese (Brazil)",
    "language.pt-PT": "Portuguese (Portugal)",
    "language.nl": "Dutch",
    "language.da": "Danish",
    "language.sv": "Swedish",
    "language.nb": "Norwegian",
    "language.fi": "Finnish",
    "language.pl": "Polish",
    "language.cs": "Czech",
    "language.hu": "Hungarian",
    "language.ro": "Romanian",
    "language.el": "Greek",
    "language.tr": "Turkish",
    "language.ru": "Russian",
    "language.uk": "Ukrainian",
    "language.ar": "Arabic",
    "language.he": "Hebrew",
    "language.hi": "Hindi",
    "language.th": "Thai",
    "language.vi": "Vietnamese",
    "language.id": "Indonesian",
    "language.ja": "Japanese",
    "language.ko": "Korean",
    "language.zh-Hans": "Simplified Chinese",
    "language.zh-Hant": "Traditional Chinese",
}

# Translations keyed by locale. Missing keys fall back only during authoring;
# the writer asserts completeness.
TR: dict[str, dict[str, str]] = {}


def add(locale: str, mapping: dict[str, str]) -> None:
    TR[locale] = mapping


add("es", {
    "app.name": "Folio", "group.organize": "Organizar", "group.reduce": "Reducir",
    "group.stamp": "Sello", "group.convert": "Convertir", "group.secure": "Seguridad",
    "recents": "Recientes", "recents.clear": "Borrar", "recents.empty": "No hay archivos recientes",
    "tool.pages": "Páginas", "tool.merge": "Combinar", "tool.split": "Dividir",
    "tool.compress": "Comprimir", "tool.watermark": "Marca de agua", "tool.pageNumbers": "Números de página",
    "tool.imagesToPDF": "Imágenes a PDF", "tool.pdfToImages": "PDF a imágenes",
    "tool.extractText": "Extraer texto", "tool.ocr": "OCR", "tool.protect": "Proteger",
    "tool.unlock": "Desbloquear", "tool.redact": "Tachar", "stage.pages": "Páginas", "stage.read": "Leer",
    "toolbar.rotate": "Girar a la derecha", "toolbar.rotateCCW": "Girar a la izquierda",
    "toolbar.delete": "Quitar del espacio de trabajo", "toolbar.addFiles": "Añadir archivos",
    "toolbar.inspector": "Inspector", "toolbar.settings": "Ajustes",
    "empty.headline": "Suelta un PDF",
    "empty.hint": "Los archivos se quedan en este Mac. Exportar no sustituye el original salvo que lo pidas.",
    "empty.drop": "Suelta PDF o imágenes, o haz clic para elegir",
    "export": "Exportar…", "export.saved": "Guardado", "export.replace": "Sustituir original",
    "export.replaceConfirm": "¿Sustituir el archivo original?",
    "export.replaceMessage": "Folio no puede deshacer esto.", "export.flatten": "Acoplar anotaciones",
    "inspector.pages": "Páginas", "inspector.size": "Tamaño", "inspector.document": "Documento",
    "compress.after": "Después", "compress.before": "Antes", "compress.preset": "Ajuste",
    "compress.small": "Pequeño (correo)", "compress.medium": "Medio", "compress.high": "Alta calidad",
    "compress.grayscale": "Escala de grises", "split.mode": "Dividir", "split.selected": "Páginas seleccionadas",
    "split.ranges": "Rangos", "split.rangesHint": "1-3, 7, 10-", "split.every": "Cada N páginas",
    "split.eachPage": "Cada página", "split.oneFilePerRange": "Un archivo por rango",
    "merge.help": "Ordena las páginas en la bandeja y exporta un solo archivo.",
    "watermark.text": "Texto de la marca", "watermark.position": "Posición",
    "watermark.position.center": "Centro", "watermark.position.tile": "Mosaico",
    "watermark.position.topLeft": "Arriba izquierda", "watermark.position.topRight": "Arriba derecha",
    "watermark.position.bottomLeft": "Abajo izquierda", "watermark.position.bottomRight": "Abajo derecha",
    "watermark.opacity": "Opacidad", "watermark.rotation": "Rotación",
    "pageNumbers.format": "Formato", "pageNumbers.format.number": "1", "pageNumbers.format.of": "1 / N",
    "pageNumbers.format.page": "Página 1", "pageNumbers.position": "Posición",
    "pageNumbers.position.headerLeft": "Encabezado izquierdo", "pageNumbers.position.headerCenter": "Encabezado centro",
    "pageNumbers.position.headerRight": "Encabezado derecho", "pageNumbers.position.footerLeft": "Pie izquierdo",
    "pageNumbers.position.footerCenter": "Pie centro", "pageNumbers.position.footerRight": "Pie derecho",
    "pageNumbers.startAt": "Empezar en", "pageNumbers.skipFirst": "Saltar la primera página",
    "images.pageSize": "Tamaño de página", "images.pageSize.imageSize": "Tamaño de la imagen",
    "images.pageSize.letter": "Carta", "images.pageSize.a4": "A4", "images.format": "Formato", "images.dpi": "PPP",
    "extract.help": "Exporta la capa de texto de estas páginas como un archivo .txt.",
    "ocr.help": "Reconoce el texto de páginas escaneadas y crea un PDF buscable. Solo en este Mac.",
    "unlock.help": "Escribe una copia desbloqueada. Folio necesita la contraseña con la que abriste el archivo.",
    "protect.password": "Contraseña", "protect.confirm": "Confirmar contraseña",
    "protect.owner": "Contraseña de propietario (opcional)",
    "redact.warning": "Las páginas tachadas se convierten en imágenes para que el texto no se pueda recuperar.",
    "redact.fill": "Relleno", "redact.fill.black": "Negro", "redact.fill.white": "Blanco",
    "redact.entirePage": "Tachar la página entera", "metadata.title": "Título", "metadata.author": "Autor",
    "metadata.subject": "Asunto", "settings.title": "Ajustes", "settings.language": "Idioma",
    "settings.language.system": "Sistema",
    "settings.language.relaunch": "El idioma se aplica la próxima vez que abras Folio.",
    "menu.open": "Abrir…", "menu.export": "Exportar…", "menu.tools": "Herramientas", "menu.help": "Ayuda de Folio",
    "command.addFiles": "Añadir archivos…", "command.export": "Exportar…", "command.palette": "Buscar",
    "error.emptyWorkspace": "Añade páginas antes de exportar.",
    "error.unreadable": "Folio no pudo leer ese archivo.", "error.encrypted": "Este PDF está bloqueado.",
    "error.writeFailed": "Folio no pudo escribir el archivo.", "error.cancelled": "Exportación cancelada.",
    "error.diskFull": "El disco está lleno.", "error.passwordMismatch": "Las contraseñas no coinciden.",
    "error.noPassword": "Introduce una contraseña.", "error.invalidRange": "Ese rango de páginas no es válido.",
    "error.outOfBounds": "Ese número de página está fuera de rango.",
    "suffix.merged": " – combinado", "suffix.part": " – parte", "suffix.compressed": " – comprimido",
    "suffix.stamped": " – sellado", "suffix.locked": " – bloqueado", "suffix.unlocked": " – desbloqueado",
    "suffix.searchable": " – buscable", "suffix.redacted": " – tachado", "suffix.page": " – página",
    "suffix.text": " – texto", "page_count": "%d páginas", "done": "Hecho", "cancel": "Cancelar", "ok": "OK",
    "password.prompt": "Este PDF está bloqueado", "password.unlock": "Contraseña",
    "pages.reverse": "Invertir orden", "pages.duplicate": "Duplicar",
    "pages.insertBlank": "Insertar página en blanco", "pages.removeBlank": "Quitar páginas en blanco",
})

# Remaining locales live in locales/*.json next to this script and are loaded below.

def write_catalog(table: dict[str, dict[str, str]]) -> None:
    strings = {}
    missing = []
    for key, english in EN.items():
        localizations = {}
        for locale in LOCALES:
            if locale == "en":
                value = english
            else:
                value = table.get(locale, {}).get(key)
                if value is None:
                    missing.append(f"{locale}:{key}")
                    value = english
            localizations[locale] = {"stringUnit": {"state": "translated", "value": value}}
        strings[key] = {"localizations": localizations}
    if missing:
        raise SystemExit(f"Missing {len(missing)} translations, e.g. {missing[:8]}")
    catalog = {"sourceLanguage": "en", "strings": strings, "version": "1.1"}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(catalog, ensure_ascii=False, indent=2) + "\n")
    print(f"Wrote {OUT} keys={len(EN)} locales={len(LOCALES)}")


PATCH = {
    "settings.copyright": {
        loc: "Copyright © 2026 TGthms & Grok"
        for loc in LOCALES
        if loc not in ("en", "Base")
    },
    "settings.repo": {
        loc: "GitHub"
        for loc in LOCALES
        if loc not in ("en", "Base")
    },
    "group.edit": {
        "es": "Editar", "fr": "Édition", "de": "Bearbeiten", "it": "Modifica",
        "pt-BR": "Editar", "pt-PT": "Editar", "nl": "Bewerken", "da": "Rediger",
        "sv": "Redigera", "nb": "Rediger", "fi": "Muokkaa", "pl": "Edycja",
        "cs": "Upravit", "hu": "Szerkesztés", "ro": "Editare", "el": "Επεξεργασία",
        "tr": "Düzenle", "ru": "Правка", "uk": "Редагування", "ar": "تحرير",
        "he": "עריכה", "hi": "संपादन", "th": "แก้ไข", "vi": "Chỉnh sửa",
        "id": "Edit", "ja": "編集", "ko": "편집", "zh-Hans": "编辑", "zh-Hant": "編輯",
    },
    "tool.edit": {
        "es": "Editar", "fr": "Éditer", "de": "Bearbeiten", "it": "Modifica",
        "pt-BR": "Editar", "pt-PT": "Editar", "nl": "Bewerken", "da": "Rediger",
        "sv": "Redigera", "nb": "Rediger", "fi": "Muokkaa", "pl": "Edytuj",
        "cs": "Upravit", "hu": "Szerkesztés", "ro": "Editează", "el": "Επεξεργασία",
        "tr": "Düzenle", "ru": "Правка", "uk": "Редагувати", "ar": "تحرير",
        "he": "עריכה", "hi": "संपादित करें", "th": "แก้ไข", "vi": "Chỉnh sửa",
        "id": "Edit", "ja": "編集", "ko": "편집", "zh-Hans": "编辑", "zh-Hant": "編輯",
    },
    "menu.save": {
        "es": "Guardar…", "fr": "Enregistrer…", "de": "Sichern …", "it": "Salva…",
        "pt-BR": "Salvar…", "pt-PT": "Guardar…", "nl": "Bewaar…", "da": "Gem…",
        "sv": "Spara…", "nb": "Lagre…", "fi": "Tallenna…", "pl": "Zachowaj…",
        "cs": "Uložit…", "hu": "Mentés…", "ro": "Salvează…", "el": "Αποθήκευση…",
        "tr": "Kaydet…", "ru": "Сохранить…", "uk": "Зберегти…", "ar": "حفظ…",
        "he": "שמור…", "hi": "सहेजें…", "th": "บันทึก…", "vi": "Lưu…",
        "id": "Simpan…", "ja": "保存…", "ko": "저장…", "zh-Hans": "存储…", "zh-Hant": "儲存…",
    },
    "edit.help": {
        loc: EN["edit.help"]
        for loc in LOCALES if loc not in ("en", "Base")
    } | {
        "zh-Hans": "像平常一样滚动 PDF。高亮和下划线跟从所选文字。绘制、文本框和裁剪用拖拽。存储会把标记写入文件。",
        "zh-Hant": "像平常一樣捲動 PDF。反白與底線跟從所選文字。繪製、文字框和裁剪用拖曳。儲存會把標記寫入檔案。",
        "ja": "PDF はいつもどおりスクロールできます。ハイライトと下線は選択したテキストに付きます。描画・テキスト・トリミングはドラッグです。保存でファイルに書き込みます。",
        "ko": "PDF는 평소처럼 스크롤하세요. 강조와 밑줄은 선택한 텍스트에 붙습니다. 그리기, 텍스트, 자르기는 드래그입니다. 저장하면 파일에 씁니다.",
        "fr": "Faites défiler le PDF comme d’habitude. Surlignage et soulignement suivent la sélection de texte. Dessin, texte et recadrage se font par glisser. Enregistrer écrit les marques dans le fichier.",
        "de": "Rollen Sie das PDF wie gewohnt. Hervorheben und Unterstreichen folgen der Textauswahl. Zeichnen, Text und Zuschnitt per Ziehen. Sichern schreibt die Markierungen in die Datei.",
        "es": "Desplace el PDF con normalidad. Resaltar y subrayar siguen la selección de texto. Dibujar, texto y recortar se hacen arrastrando. Guardar escribe las marcas en el archivo.",
    },
    "edit.select": {
        "es": "Seleccionar", "fr": "Sélection", "de": "Auswählen", "it": "Seleziona",
        "pt-BR": "Selecionar", "pt-PT": "Selecionar", "nl": "Selecteren", "da": "Vælg",
        "sv": "Markera", "nb": "Velg", "fi": "Valitse", "pl": "Zaznacz",
        "cs": "Vybrat", "hu": "Kijelölés", "ro": "Selectează", "el": "Επιλογή",
        "tr": "Seç", "ru": "Выбор", "uk": "Вибір", "ar": "تحديد",
        "he": "בחירה", "hi": "चुनें", "th": "เลือก", "vi": "Chọn",
        "id": "Pilih", "ja": "選択", "ko": "선택", "zh-Hans": "选择", "zh-Hant": "選取",
    },
    "edit.highlight": {
        "es": "Resaltar", "fr": "Surligner", "de": "Hervorheben", "it": "Evidenzia",
        "pt-BR": "Realçar", "pt-PT": "Realçar", "nl": "Markeren", "da": "Fremhæv",
        "sv": "Markera", "nb": "Uthev", "fi": "Korosta", "pl": "Wyróżnij",
        "cs": "Zvýraznit", "hu": "Kiemelés", "ro": "Evidențiază", "el": "Επισήμανση",
        "tr": "Vurgula", "ru": "Выделение", "uk": "Виділити", "ar": "تمييز",
        "he": "הדגש", "hi": "हाइलाइट", "th": "เน้น", "vi": "Tô",
        "id": "Sorot", "ja": "ハイライト", "ko": "강조", "zh-Hans": "高亮", "zh-Hant": "反白",
    },
    "edit.underline": {
        "es": "Subrayar", "fr": "Souligner", "de": "Unterstreichen", "it": "Sottolinea",
        "pt-BR": "Sublinhar", "pt-PT": "Sublinhar", "nl": "Onderstrepen", "da": "Understreg",
        "sv": "Understryk", "nb": "Understrek", "fi": "Alleviivaa", "pl": "Podkreśl",
        "cs": "Podtrhnout", "hu": "Aláhúzás", "ro": "Subliniază", "el": "Υπογράμμιση",
        "tr": "Altı çizili", "ru": "Подчёркивание", "uk": "Підкреслити", "ar": "تسطير",
        "he": "קו תחתון", "hi": "रेखांकित", "th": "ขีดเส้นใต้", "vi": "Gạch dưới",
        "id": "Garis bawah", "ja": "下線", "ko": "밑줄", "zh-Hans": "下划线", "zh-Hant": "底線",
    },
    "edit.textBox": {
        "es": "Cuadro de texto", "fr": "Zone de texte", "de": "Textfeld", "it": "Casella di testo",
        "pt-BR": "Caixa de texto", "pt-PT": "Caixa de texto", "nl": "Tekstvak", "da": "Tekstboks",
        "sv": "Textruta", "nb": "Tekstboks", "fi": "Tekstiruutu", "pl": "Pole tekstowe",
        "cs": "Textové pole", "hu": "Szövegdoboz", "ro": "Casetă text", "el": "Πλαίσιο κειμένου",
        "tr": "Metin kutusu", "ru": "Надпись", "uk": "Текстове поле", "ar": "مربع نص",
        "he": "תיבת טקסט", "hi": "पाठ बॉक्स", "th": "กล่องข้อความ", "vi": "Hộp chữ",
        "id": "Kotak teks", "ja": "テキストボックス", "ko": "텍스트 상자", "zh-Hans": "文本框", "zh-Hant": "文字框",
    },
    "edit.draw": {
        "es": "Dibujar", "fr": "Dessiner", "de": "Zeichnen", "it": "Disegna",
        "pt-BR": "Desenhar", "pt-PT": "Desenhar", "nl": "Teken", "da": "Tegn",
        "sv": "Rita", "nb": "Tegn", "fi": "Piirrä", "pl": "Rysuj",
        "cs": "Kreslit", "hu": "Rajzolás", "ro": "Desenează", "el": "Σχεδίαση",
        "tr": "Çiz", "ru": "Перо", "uk": "Малювати", "ar": "رسم",
        "he": "ציور", "hi": "आरेखित करें", "th": "วาด", "vi": "Vẽ",
        "id": "Gambar", "ja": "描画", "ko": "그리기", "zh-Hans": "绘制", "zh-Hant": "繪製",
    },
    "edit.cropMode": {
        "es": "Recortar", "fr": "Recadrer", "de": "Zuschneiden", "it": "Ritaglia",
        "pt-BR": "Recortar", "pt-PT": "Recortar", "nl": "Bijsnijden", "da": "Beskær",
        "sv": "Beskär", "nb": "Beskjær", "fi": "Rajaa", "pl": "Przytnij",
        "cs": "Oříznout", "hu": "Levágás", "ro": "Decupează", "el": "Περικοπή",
        "tr": "Kırp", "ru": "Обрезать", "uk": "Обрізати", "ar": "اقتصاص",
        "he": "חיתוך", "hi": "क्रॉप", "th": "ครอป", "vi": "Cắt",
        "id": "Pangkas", "ja": "トリミング", "ko": "자르기", "zh-Hans": "裁剪", "zh-Hant": "裁剪",
    },
    "command.save": {
        "es": "Guardar", "fr": "Enregistrer", "de": "Sichern", "it": "Salva",
        "pt-BR": "Salvar", "pt-PT": "Guardar", "nl": "Bewaar", "da": "Gem",
        "sv": "Spara", "nb": "Lagre", "fi": "Tallenna", "pl": "Zachowaj",
        "cs": "Uložit", "hu": "Mentés", "ro": "Salvează", "el": "Αποθήκευση",
        "tr": "Kaydet", "ru": "Сохранить", "uk": "Зберегти", "ar": "حفظ",
        "he": "שמור", "hi": "सहेजें", "th": "บันทึก", "vi": "Lưu",
        "id": "Simpan", "ja": "保存", "ko": "저장", "zh-Hans": "存储", "zh-Hant": "儲存",
    },
    "edit.crop": {
        loc: "Crop selected pages" for loc in LOCALES if loc not in ("en", "Base")
    } | {"zh-Hans": "裁剪所选页面", "zh-Hant": "裁剪所選頁面", "ja": "選択したページをトリミング", "ko": "선택한 페이지 자르기",
         "fr": "Recadrer les pages sélectionnées", "de": "Ausgewählte Seiten zuschneiden", "es": "Recortar páginas seleccionadas"},
    "edit.clearCrop": {
        loc: "Clear crop" for loc in LOCALES if loc not in ("en", "Base")
    } | {"zh-Hans": "清除裁剪", "zh-Hant": "清除裁剪", "ja": "トリミングを解除", "ko": "자르기 지우기",
         "fr": "Effacer le recadrage", "de": "Zuschnitt entfernen", "es": "Quitar recorte"},
    "edit.replaceImage": {
        loc: "Replace page with image…" for loc in LOCALES if loc not in ("en", "Base")
    } | {"zh-Hans": "用图片替换页面…", "zh-Hant": "用影像取代頁面…", "ja": "ページを画像で置き換える…", "ko": "이미지로 페이지 바꾸기…",
         "fr": "Remplacer la page par une image…", "de": "Seite durch Bild ersetzen …", "es": "Reemplazar página por imagen…"},
    "edit.clearMarks": {
        loc: "Clear marks on selection" for loc in LOCALES if loc not in ("en", "Base")
    } | {"zh-Hans": "清除所选标记", "zh-Hant": "清除所選標記", "ja": "選択のマークを消去", "ko": "선택 표시 지우기",
         "fr": "Effacer les marques de la sélection", "de": "Markierungen der Auswahl löschen", "es": "Borrar marcas de la selección"},
    "edit.textPrompt": {
        "es": "Texto", "fr": "Texte", "de": "Text", "it": "Testo",
        "pt-BR": "Texto", "pt-PT": "Texto", "nl": "Tekst", "da": "Tekst",
        "sv": "Text", "nb": "Tekst", "fi": "Teksti", "pl": "Tekst",
        "cs": "Text", "hu": "Szöveg", "ro": "Text", "el": "Κείμενο",
        "tr": "Metin", "ru": "Текст", "uk": "Текст", "ar": "نص",
        "he": "טקסט", "hi": "पाठ", "th": "ข้อความ", "vi": "Chữ",
        "id": "Teks", "ja": "テキスト", "ko": "텍스트", "zh-Hans": "文本", "zh-Hant": "文字",
    },
    "suffix.edited": {
        loc: " – edited" for loc in LOCALES if loc not in ("en", "Base")
    } | {"zh-Hans": " – 已编辑", "zh-Hant": " – 已編輯", "ja": " – 編集済み", "ko": " – 편집됨",
         "fr": " – modifié", "de": " – bearbeitet", "es": " – editado"},
    "size.zero": {loc: "0 KB" for loc in LOCALES if loc not in ("en", "Base")},
    "size.bytesUnit": {loc: "bytes" for loc in LOCALES if loc not in ("en", "Base")} | {
        "zh-Hans": "字节", "zh-Hant": "位元組", "ja": "バイト", "ko": "바이트",
    },
    "size.kb": {loc: "KB" for loc in LOCALES if loc not in ("en", "Base")},
    "size.mb": {loc: "MB" for loc in LOCALES if loc not in ("en", "Base")},
    "size.gb": {loc: "GB" for loc in LOCALES if loc not in ("en", "Base")},
    **{
        f"language.{code}": (
            {loc: EN[f"language.{code}"] for loc in LOCALES if loc not in ("en", "Base")}
            | {
                "zh-Hans": {
                    "en": "英语", "es": "西班牙语", "fr": "法语", "de": "德语", "it": "意大利语",
                    "pt-BR": "葡萄牙语（巴西）", "pt-PT": "葡萄牙语（葡萄牙）", "nl": "荷兰语",
                    "da": "丹麦语", "sv": "瑞典语", "nb": "挪威语", "fi": "芬兰语", "pl": "波兰语",
                    "cs": "捷克语", "hu": "匈牙利语", "ro": "罗马尼亚语", "el": "希腊语", "tr": "土耳其语",
                    "ru": "俄语", "uk": "乌克兰语", "ar": "阿拉伯语", "he": "希伯来语", "hi": "印地语",
                    "th": "泰语", "vi": "越南语", "id": "印度尼西亚语", "ja": "日语", "ko": "韩语",
                    "zh-Hans": "简体中文", "zh-Hant": "繁体中文",
                }[code],
                "zh-Hant": {
                    "en": "英語", "es": "西班牙語", "fr": "法語", "de": "德語", "it": "義大利語",
                    "pt-BR": "葡萄牙語（巴西）", "pt-PT": "葡萄牙語（葡萄牙）", "nl": "荷蘭語",
                    "da": "丹麥語", "sv": "瑞典語", "nb": "挪威語", "fi": "芬蘭語", "pl": "波蘭語",
                    "cs": "捷克語", "hu": "匈牙利語", "ro": "羅馬尼亞語", "el": "希臘語", "tr": "土耳其語",
                    "ru": "俄語", "uk": "烏克蘭語", "ar": "阿拉伯語", "he": "希伯來語", "hi": "印地語",
                    "th": "泰語", "vi": "越南語", "id": "印尼語", "ja": "日語", "ko": "韓語",
                    "zh-Hans": "簡體中文", "zh-Hant": "繁體中文",
                }[code],
                "fr": {
                    "en": "Anglais", "es": "Espagnol", "fr": "Français", "de": "Allemand", "it": "Italien",
                    "pt-BR": "Portugais (Brésil)", "pt-PT": "Portugais (Portugal)", "nl": "Néerlandais",
                    "da": "Danois", "sv": "Suédois", "nb": "Norvégien", "fi": "Finnois", "pl": "Polonais",
                    "cs": "Tchèque", "hu": "Hongrois", "ro": "Roumain", "el": "Grec", "tr": "Turc",
                    "ru": "Russe", "uk": "Ukrainien", "ar": "Arabe", "he": "Hébreu", "hi": "Hindi",
                    "th": "Thaï", "vi": "Vietnamien", "id": "Indonésien", "ja": "Japonais", "ko": "Coréen",
                    "zh-Hans": "Chinois simplifié", "zh-Hant": "Chinois traditionnel",
                }[code],
            }
        )
        for code in [
            "en", "es", "fr", "de", "it", "pt-BR", "pt-PT", "nl", "da", "sv", "nb", "fi",
            "pl", "cs", "hu", "ro", "el", "tr", "ru", "uk", "ar", "he", "hi", "th", "vi",
            "id", "ja", "ko", "zh-Hans", "zh-Hant",
        ]
    },
    "settings.language.relaunch": {
        "es": "El idioma de la interfaz cambia al elegirlo.",
        "fr": "La langue de l’interface change dès que vous en choisissez une.",
        "de": "Die Sprache der Oberfläche ändert sich, sobald Sie eine wählen.",
        "it": "La lingua dell’interfaccia si aggiorna quando ne scegli una.",
        "pt-BR": "O idioma da interface muda quando você escolhe um.",
        "pt-PT": "O idioma da interface muda quando escolhe um.",
        "nl": "De interfacetaal verandert zodra je er een kiest.",
        "da": "Grænsefladesproget skifter, når du vælger et.",
        "sv": "Gränssnittsspråket uppdateras när du väljer ett.",
        "nb": "Grensesnittspråket oppdateres når du velger et.",
        "fi": "Käyttöliittymän kieli vaihtuu, kun valitset kielen.",
        "pl": "Język interfejsu zmienia się po wybraniu.",
        "cs": "Jazyk rozhraní se změní hned po výběru.",
        "hu": "A felület nyelve a választás után azonnal vált.",
        "ro": "Limba interfeței se schimbă când alegi una.",
        "el": "Η γλώσσα της διεπαφής αλλάζει μόλις επιλέξετε μία.",
        "tr": "Arayüz dili birini seçtiğinizde güncellenir.",
        "ru": "Язык интерфейса меняется сразу после выбора.",
        "uk": "Мова інтерфейсу змінюється одразу після вибору.",
        "ar": "تتغير لغة الواجهة عند اختيار لغة.",
        "he": "שפת הממשק מתעדכנת כשבוחרים אחת.",
        "hi": "भाषा चुनते ही इंटरफ़ेस की भाषा बदल जाती है।",
        "th": "ภาษาของอินเทอร์เฟซเปลี่ยนเมื่อคุณเลือก",
        "vi": "Ngôn ngữ giao diện đổi ngay khi bạn chọn.",
        "id": "Bahasa antarmuka berubah saat Anda memilih.",
        "ja": "言語を選ぶと、すぐに表示が切り替わります。",
        "ko": "언어를 고르면 인터페이스가 바로 바뀝니다.",
        "zh-Hans": "选择语言后，界面会立即切换。",
        "zh-Hant": "選擇語言後，介面會立即切換。",
    },
    "pages.selectRange": {
        "es": "Seleccionar",
        "fr": "Sélectionner",
        "de": "Auswählen",
        "it": "Seleziona",
        "pt-BR": "Selecionar",
        "pt-PT": "Selecionar",
        "nl": "Selecteren",
        "da": "Vælg",
        "sv": "Markera",
        "nb": "Velg",
        "fi": "Valitse",
        "pl": "Zaznacz",
        "cs": "Vybrat",
        "hu": "Kijelölés",
        "ro": "Selectează",
        "el": "Επιλογή",
        "tr": "Seç",
        "ru": "Выбрать",
        "uk": "Вибрати",
        "ar": "تحديد",
        "he": "בחר",
        "hi": "चुनें",
        "th": "เลือก",
        "vi": "Chọn",
        "id": "Pilih",
        "ja": "選択",
        "ko": "선택",
        "zh-Hans": "选择",
        "zh-Hant": "選取",
    },
    "pages.selectRangeHint": {
        "es": "Páginas o intervalos",
        "fr": "Pages ou plages",
        "de": "Seiten oder Bereiche",
        "it": "Pagine o intervalli",
        "pt-BR": "Páginas ou intervalos",
        "pt-PT": "Páginas ou intervalos",
        "nl": "Pagina’s of bereiken",
        "da": "Sider eller intervaller",
        "sv": "Sidor eller intervall",
        "nb": "Sider eller intervaller",
        "fi": "Sivut tai alueet",
        "pl": "Strony lub zakresy",
        "cs": "Stránky nebo rozsahy",
        "hu": "Oldalak vagy tartományok",
        "ro": "Pagini sau intervale",
        "el": "Σελίδες ή εύρη",
        "tr": "Sayfalar veya aralıklar",
        "ru": "Страницы или диапазоны",
        "uk": "Сторінки або діапазони",
        "ar": "صفحات أو نطاقات",
        "he": "עמודים או טווחים",
        "hi": "पृष्ठ या सीमाएँ",
        "th": "หน้าหรือช่วง",
        "vi": "Trang hoặc khoảng",
        "id": "Halaman atau rentang",
        "ja": "ページまたは範囲",
        "ko": "페이지 또는 범위",
        "zh-Hans": "页码或范围",
        "zh-Hant": "頁碼或範圍",
    },
    "pages.selectRangeHelp": {
        "es": "Escribe números de página o intervalos. Eliminar y otras acciones usan esta selección.",
        "fr": "Saisissez des numéros ou des plages. Supprimer et les autres actions s’appliquent à cette sélection.",
        "de": "Geben Sie Seitenzahlen oder Bereiche ein. Löschen und andere Aktionen gelten für diese Auswahl.",
        "it": "Inserisci numeri di pagina o intervalli. Elimina e le altre azioni usano questa selezione.",
        "pt-BR": "Digite números de página ou intervalos. Excluir e outras ações usam esta seleção.",
        "pt-PT": "Introduza números de página ou intervalos. Eliminar e outras ações usam esta seleção.",
        "nl": "Typ paginanummers of bereiken. Verwijderen en andere acties gebruiken deze selectie.",
        "da": "Skriv sidenumre eller intervaller. Slet og andre handlinger bruger dette valg.",
        "sv": "Skriv sidnummer eller intervall. Radera och andra åtgärder använder det här urvalet.",
        "nb": "Skriv sidenummer eller intervaller. Slett og andre handlinger bruker dette utvalget.",
        "fi": "Kirjoita sivunumerot tai alueet. Poisto ja muut toiminnot käyttävät tätä valintaa.",
        "pl": "Wpisz numery stron lub zakresy. Usuwanie i inne działania używają tego zaznaczenia.",
        "cs": "Zadejte čísla stránek nebo rozsahy. Mazání a další akce použijí tento výběr.",
        "hu": "Írjon oldalszámokat vagy tartományokat. A törlés és más műveletek ezt a kijelölést használják.",
        "ro": "Tastează numere de pagină sau intervale. Ștergerea și celelalte acțiuni folosesc această selecție.",
        "el": "Πληκτρολογήστε αριθμούς σελίδων ή εύρη. Η διαγραφή και οι άλλες ενέργειες χρησιμοποιούν αυτή την επιλογή.",
        "tr": "Sayfa numaraları veya aralıklar yazın. Silme ve diğer işlemler bu seçimi kullanır.",
        "ru": "Введите номера страниц или диапазоны. Удаление и другие действия применяются к этому выбору.",
        "uk": "Введіть номери сторінок або діапазони. Вилучення та інші дії застосовують цей вибір.",
        "ar": "اكتب أرقام الصفحات أو النطاقات. الحذف والإجراءات الأخرى تستخدم هذا التحديد.",
        "he": "הקלידו מספרי עמוד או טווחים. מחיקה ופעולות אחרות משתמשות בבחירה הזו.",
        "hi": "पृष्ठ संख्या या सीमाएँ लिखें। हटाना और अन्य क्रियाएँ इसी चयन पर लागू होती हैं।",
        "th": "พิมพ์เลขหน้าหรือช่วง การลบและการทำงานอื่นใช้การเลือกนี้",
        "vi": "Nhập số trang hoặc khoảng. Xóa và thao tác khác dùng phần chọn này.",
        "id": "Ketik nomor halaman atau rentang. Hapus dan tindakan lain memakai pilihan ini.",
        "ja": "ページ番号や範囲を入力します。削除などの操作はこの選択に対して行われます。",
        "ko": "페이지 번호나 범위를 입력하세요. 삭제와 다른 동작은 이 선택에 적용됩니다.",
        "zh-Hans": "输入页码或范围。删除和其他操作会作用于这次选择。",
        "zh-Hant": "輸入頁碼或範圍。刪除和其他動作會套用到這次選取。",
    },
    "inspector.encrypted": {
        "es": "Cifrado", "fr": "Chiffré", "de": "Verschlüsselt", "it": "Crittografato",
        "pt-BR": "Criptografado", "pt-PT": "Encriptado", "nl": "Versleuteld", "da": "Krypteret",
        "sv": "Krypterad", "nb": "Kryptert", "fi": "Salattu", "pl": "Zaszyfrowany",
        "cs": "Šifrováno", "hu": "Titkosított", "ro": "Criptat", "el": "Κρυπτογραφημένο",
        "tr": "Şifreli", "ru": "Зашифрован", "uk": "Зашифровано", "ar": "مشفّر",
        "he": "מוצפן", "hi": "एन्क्रिप्टेड", "th": "เข้ารหัส", "vi": "Đã mã hóa",
        "id": "Terenkripsi", "ja": "暗号化", "ko": "암호화됨", "zh-Hans": "已加密", "zh-Hant": "已加密",
    },
    "inspector.yes": {
        "es": "Sí", "fr": "Oui", "de": "Ja", "it": "Sì", "pt-BR": "Sim", "pt-PT": "Sim",
        "nl": "Ja", "da": "Ja", "sv": "Ja", "nb": "Ja", "fi": "Kyllä", "pl": "Tak",
        "cs": "Ano", "hu": "Igen", "ro": "Da", "el": "Ναι", "tr": "Evet", "ru": "Да",
        "uk": "Так", "ar": "نعم", "he": "כן", "hi": "हाँ", "th": "ใช่", "vi": "Có",
        "id": "Ya", "ja": "はい", "ko": "예", "zh-Hans": "是", "zh-Hant": "是",
    },
    "inspector.no": {
        "es": "No", "fr": "Non", "de": "Nein", "it": "No", "pt-BR": "Não", "pt-PT": "Não",
        "nl": "Nee", "da": "Nej", "sv": "Nej", "nb": "Nei", "fi": "Ei", "pl": "Nie",
        "cs": "Ne", "hu": "Nem", "ro": "Nu", "el": "Όχι", "tr": "Hayır", "ru": "Нет",
        "uk": "Ні", "ar": "لا", "he": "לא", "hi": "नहीं", "th": "ไม่", "vi": "Không",
        "id": "Tidak", "ja": "いいえ", "ko": "아니요", "zh-Hans": "否", "zh-Hant": "否",
    },
    "menu.print": {
        "es": "Imprimir…", "fr": "Imprimer…", "de": "Drucken …", "it": "Stampa…",
        "pt-BR": "Imprimir…", "pt-PT": "Imprimir…", "nl": "Druk af…", "da": "Udskriv…",
        "sv": "Skriv ut…", "nb": "Skriv ut…", "fi": "Tulosta…", "pl": "Drukuj…",
        "cs": "Tisk…", "hu": "Nyomtatás…", "ro": "Tipărește…", "el": "Εκτύπωση…",
        "tr": "Yazdır…", "ru": "Печать…", "uk": "Друкувати…", "ar": "طباعة…",
        "he": "הדפס…", "hi": "प्रिंट…", "th": "พิมพ์…", "vi": "In…",
        "id": "Cetak…", "ja": "プリント…", "ko": "프린트…", "zh-Hans": "打印…", "zh-Hant": "列印…",
    },
    "menu.go": {
        "es": "Ir", "fr": "Aller", "de": "Gehe zu", "it": "Vai", "pt-BR": "Ir", "pt-PT": "Ir",
        "nl": "Ga", "da": "Gå", "sv": "Gå", "nb": "Gå", "fi": "Siirry", "pl": "Idź",
        "cs": "Přejít", "hu": "Ugrás", "ro": "Du-te", "el": "Μετάβαση", "tr": "Git", "ru": "Переход",
        "uk": "Перейти", "ar": "انتقال", "he": "מעבר", "hi": "जाएँ", "th": "ไป", "vi": "Đi tới",
        "id": "Buka", "ja": "移動", "ko": "이동", "zh-Hans": "转到", "zh-Hant": "前往",
    },
    "nav.next": {
        "es": "Página siguiente", "fr": "Page suivante", "de": "Nächste Seite", "it": "Pagina successiva",
        "pt-BR": "Próxima página", "pt-PT": "Página seguinte", "nl": "Volgende pagina", "da": "Næste side",
        "sv": "Nästa sida", "nb": "Neste side", "fi": "Seuraava sivu", "pl": "Następna strona",
        "cs": "Další stránka", "hu": "Következő oldal", "ro": "Pagina următoare", "el": "Επόμενη σελίδα",
        "tr": "Sonraki sayfa", "ru": "Следующая страница", "uk": "Наступна сторінка", "ar": "الصفحة التالية",
        "he": "העמוד הבא", "hi": "अगला पृष्ठ", "th": "หน้าถัดไป", "vi": "Trang sau",
        "id": "Halaman berikutnya", "ja": "次のページ", "ko": "다음 페이지", "zh-Hans": "下一页", "zh-Hant": "下一頁",
    },
    "nav.previous": {
        "es": "Página anterior", "fr": "Page précédente", "de": "Vorherige Seite", "it": "Pagina precedente",
        "pt-BR": "Página anterior", "pt-PT": "Página anterior", "nl": "Vorige pagina", "da": "Forrige side",
        "sv": "Föregående sida", "nb": "Forrige side", "fi": "Edellinen sivu", "pl": "Poprzednia strona",
        "cs": "Předchozí stránka", "hu": "Előző oldal", "ro": "Pagina anterioară", "el": "Προηγούμενη σελίδα",
        "tr": "Önceki sayfa", "ru": "Предыдущая страница", "uk": "Попередня сторінка", "ar": "الصفحة السابقة",
        "he": "העמוד הקודם", "hi": "पिछला पृष्ठ", "th": "หน้าก่อน", "vi": "Trang trước",
        "id": "Halaman sebelumnya", "ja": "前のページ", "ko": "이전 페이지", "zh-Hans": "上一页", "zh-Hant": "上一頁",
    },
    "nav.first": {
        "es": "Primera página", "fr": "Première page", "de": "Erste Seite", "it": "Prima pagina",
        "pt-BR": "Primeira página", "pt-PT": "Primeira página", "nl": "Eerste pagina", "da": "Første side",
        "sv": "Första sidan", "nb": "Første side", "fi": "Ensimmäinen sivu", "pl": "Pierwsza strona",
        "cs": "První stránka", "hu": "Első oldal", "ro": "Prima pagină", "el": "Πρώτη σελίδα",
        "tr": "İlk sayfa", "ru": "Первая страница", "uk": "Перша сторінка", "ar": "الصفحة الأولى",
        "he": "העמוד הראשון", "hi": "पहला पृष्ठ", "th": "หน้าแรก", "vi": "Trang đầu",
        "id": "Halaman pertama", "ja": "最初のページ", "ko": "첫 페이지", "zh-Hans": "第一页", "zh-Hant": "第一頁",
    },
    "nav.last": {
        "es": "Última página", "fr": "Dernière page", "de": "Letzte Seite", "it": "Ultima pagina",
        "pt-BR": "Última página", "pt-PT": "Última página", "nl": "Laatste pagina", "da": "Sidste side",
        "sv": "Sista sidan", "nb": "Siste side", "fi": "Viimeinen sivu", "pl": "Ostatnia strona",
        "cs": "Poslední stránka", "hu": "Utolsó oldal", "ro": "Ultima pagină", "el": "Τελευταία σελίδα",
        "tr": "Son sayfa", "ru": "Последняя страница", "uk": "Остання сторінка", "ar": "الصفحة الأخيرة",
        "he": "העמוד האחרון", "hi": "अंतिम पृष्ठ", "th": "หน้าสุดท้าย", "vi": "Trang cuối",
        "id": "Halaman terakhir", "ja": "最後のページ", "ko": "마지막 페이지", "zh-Hans": "最后一页", "zh-Hant": "最後一頁",
    },
    "nav.selectAll": {
        "es": "Seleccionar todas las páginas", "fr": "Sélectionner toutes les pages", "de": "Alle Seiten auswählen",
        "it": "Seleziona tutte le pagine", "pt-BR": "Selecionar todas as páginas", "pt-PT": "Selecionar todas as páginas",
        "nl": "Alle pagina’s selecteren", "da": "Vælg alle sider", "sv": "Markera alla sidor", "nb": "Velg alle sider",
        "fi": "Valitse kaikki sivut", "pl": "Zaznacz wszystkie strony", "cs": "Vybrat všechny stránky",
        "hu": "Összes oldal kijelölése", "ro": "Selectează toate paginile", "el": "Επιλογή όλων των σελίδων",
        "tr": "Tüm sayfaları seç", "ru": "Выбрать все страницы", "uk": "Вибрати всі сторінки",
        "ar": "تحديد كل الصفحات", "he": "בחר את כל העמודים", "hi": "सभी पृष्ठ चुनें", "th": "เลือกทุกหน้า",
        "vi": "Chọn mọi trang", "id": "Pilih semua halaman", "ja": "すべてのページを選択",
        "ko": "모든 페이지 선택", "zh-Hans": "选择所有页面", "zh-Hant": "選取所有頁面",
    },
}

if __name__ == "__main__":
    extra = Path(__file__).with_name("locales.json")
    if extra.exists():
        loaded = json.loads(extra.read_text())
        for loc, mapping in loaded.items():
            TR.setdefault(loc, {}).update(mapping)
    for key, per_locale in PATCH.items():
        for loc, value in per_locale.items():
            TR.setdefault(loc, {})[key] = value
    write_catalog(TR)
